export const GET_PERSONALCOUNT_SUCCESS = 'GET_PERSONALCOUNT_SUCCESS';   // 登录成功
export const GET_PERSONALCOUNT_ERROR = 'GET_PERSONALCOUNT_ERROR';   // 登录用户
export const UPDATE_PERSONALCOUNT = 'UPDATE_PERSONALCOUNT'; // 登出成功