import { StyleSheet } from 'react-native'
import { ScreenUtil } from '../../../utils/util'
const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#fafbfc'
    },
    goback: {
        marginRight: ScreenUtil.scaleSize(30),
        fontSize: ScreenUtil.setSpText(16)
    },
    rewardDetail_title:{
        backgroundColor:'#fff',
        paddingTop:ScreenUtil.scaleSize(30),
        paddingBottom:ScreenUtil.scaleSize(30),
        flexDirection:'column'
    },
    rewardDetail_title_text:{
        fontSize:30,
        color:'#292929',
        paddingLeft:ScreenUtil.scaleSize(50),
        marginBottom:ScreenUtil.scaleSize(30)
    },
    rewardDetail_con:{
        paddingLeft:ScreenUtil.scaleSize(30),
        paddingRight:ScreenUtil.scaleSize(30),
        backgroundColor:'#fafbfc',
        borderRadius:ScreenUtil.scaleSize(20)
    },
    rewardtask_title_box:{
        paddingLeft:ScreenUtil.scaleSize(30),
        height: ScreenUtil.scaleSize(115),
        borderBottomWidth:1,
        borderStyle:'solid',
        borderBottomColor:'#e6e6e6',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    rewardtask_title:{
        width:ScreenUtil.scaleSize(450),
        fontSize:20,
        color:'#292929',
    },
    rewardtask_state:{
        width: ScreenUtil.scaleSize(110),
        height: ScreenUtil.scaleSize(115),
    },
    rewardtask_item_con:{

    },
    rewardtask_item_con_item_box:{
        flexDirection:'column',
        paddingTop:ScreenUtil.scaleSize(30),
    },
    rewardtask_item_con_item_box_border:{
        borderBottomColor:'#e6e6e6',
        borderStyle:'solid',
        borderBottomWidth:1
    },
    rewardtask_item_con_item:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingBottom:ScreenUtil.scaleSize(30),
    },
    rewardtask_item_con_list:{
        flexDirection:'row',
        alignItems:'center',
    },
    rewardtask_item_con_bg:{
        width:ScreenUtil.scaleSize(40),
        height:ScreenUtil.scaleSize(40),
    },
    rewardtask_item_con_list_title:{
        fontSize:16,
        color:'#4d4d4d'
    },
    rewardtask_item_con_list_sing:{
        color:'#668fff',
        fontSize:14,
    },
    rewardtask_item_con_list_price:{
        color:'#668fff',
        fontSize:22,
    },
    rewardtask_item_con_list_time:{
        fontSize:16,
        color:'#808080'
    },
    rewardDetail_box:{
        marginTop:ScreenUtil.scaleSize(30),
        backgroundColor:'#fff',
        paddingLeft:ScreenUtil.scaleSize(30),
        paddingRight:ScreenUtil.scaleSize(30),
    },
    rewardDetail_box_title:{
        height:ScreenUtil.scaleSize(100),
        paddingLeft:ScreenUtil.scaleSize(20),
        flexDirection:'row',
        alignItems:'center',
        borderStyle:'solid',
        borderBottomColor:'#e6e6e6',
        borderBottomWidth:1,
    },
    rewardDetail_box_title_bg:{
        borderStyle:'solid',
        borderLeftColor:'#668fff',
        borderLeftWidth:4,
        height: ScreenUtil.scaleSize(30),
        marginRight:ScreenUtil.scaleSize(20)
    },
    rewardDetail_box_title_text:{
        fontSize:18,
        color:'#4d4d4d'
    },
    rewardDetail_box_info:{

    },
    info_suspect:{
        flexDirection:'column',
        paddingTop:ScreenUtil.scaleSize(20),
        paddingBottom:ScreenUtil.scaleSize(20),
    },
    info_suspect_item:{
        height:ScreenUtil.scaleSize(50),
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    info_suspect_info:{
        fontSize:16,
        color:'#4d4d4d'
    },
    rewardDetail_box_btn:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingLeft:ScreenUtil.scaleSize(60),
        paddingRight:ScreenUtil.scaleSize(60),
        marginTop:ScreenUtil.scaleSize(30),
        marginBottom:ScreenUtil.scaleSize(50),
        /*position:'absolute',
        bottom:ScreenUtil.scaleSize(30),
        left:ScreenUtil.scaleSize(60),*/
    },
    rewardDetail_box_btn_opr:{
        paddingLeft:ScreenUtil.scaleSize(80),
        paddingRight:ScreenUtil.scaleSize(80),
        height:ScreenUtil.scaleSize(90),
        backgroundColor:'#668fff',
        borderRadius:ScreenUtil.scaleSize(50),
        alignItems:'center',
        justifyContent:'center',
    },
    rewardDetail_box_btn_oprother:{
        backgroundColor:'#7d8edb',
    },
    rewardDetail_box_btn_opr_text:{
        fontSize:20,
        color:'#fff'
    },


})
export default styles