export const SUCCESS_REWARD_DETAIL = 'SUCCESS_REWARD_DETAIL';
export const UPDATE_SUSPECTJSON_SUCCESS = 'UPDATE_SUSPECTJSON_SUCCESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_LAW_SUCCESS = 'UPDATE_LAW_SUCCESS';